# Prefix Key
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# History 

set -g history-limit 9999999
set -g mouse on
unbind -n MouseDrag1Pane

# Reloads
bind-key r source-file  ~/.tmux.conf \; display-message "Tmux Config Reloaded."

#Spliting the woindow
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Pane Switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Mouse Mode
set -g mouse on

# Terminal Colors

set -g default-terminal "tmux-256color"

# Renumbering
set -g renumber-windows on

# Renaming
set-option -g allow-rename off

# Bell Rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Clock Mode
setw -g clock-mode-color yellow

# Copy Mode
setw -g mode-style 'fg=black bg=red bold'

# Panes 
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# Statusbar
set -g status-left ""
set -gF status-right "#{E:@catppuccin_status_session}"

set -agF status-right "#{E:@catppuccin_status_application}"

set -agF status-right "#{@catppuccin_status_directory}"

set -agF status-right "#{E:@catppuccin_status_date_time}"
set -g window-status-separator ""
set -gF window-status-format "#[bg=#{@ctp_surface_1},fg=#{@ctp_fg}] ##I ##T "
set -gF window-status-current-format "#[bg=#{@ctp_mauve},fg=#{@ctp_crust}] ##I ##T "

set -g status-right-length 400
# Plugins 

set -g @plugin 'tmux-plugins/'
set -g @plugin 'tmux-plugins/sensible'


run '~/.tmux/plugins/tpm/tpm'

set -g @plugin 'tmux-plugins/tmux-logging'

set -g @logging-path '#{pane_current_path}'
set -g @save-complete-history-path '#{pane_current_path}'
set -g @screen-capture-path '#{pane_current_path}'

set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'spywhere/tmux-named-snapshot'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin '2kabhishek/tmux-tea'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-cpu'
# Catpuccin Theme



set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_current_number_color "#{@thm_lavender}"
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_window_flags "yes"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_window_flags_icon_current " 󰖯"
set -g @catppuccin_window_flags_icon_activity " 󱅫"
set -g @catppuccin_window_flags_icon_silent " 󰂛" # ~
set -g @catppuccin_window_flags_icon_last " 󰖰" # -
set -g @catppuccin_status_module_bg_color "#{@thm_surface_0}"
set -g @catppuccin_pane_border_status "yes"

set -g @catppuccin_date_time_text "%Y-%m-%d %I:%M %P"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_default_text " #{window_name}"
set -g @catppuccin_window_current_fill "all"
run ~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Plugin Info
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -g @session-wizard 'K'
set -g @session-wizard-mode 'short-path'
set -g @session-wizard-windows on
